### ISSUE TITLE
Create the Graphical User interface (GUI) on Figma.com

### ISSUE THREAD

**Issue by Oisavictor** [Oisavictor/CGPA-Web-Calculator#1]
Create the GUI for the CGPA Calculator on Figma.com showing the various components and assets to be used in the web app development.

**Comment by Oisavictor** [comment]
please check out this link to access the Figma design: https://www.figma.com/file/wzB1i6sBaI00wwkhOQXRZx/EDSU-team-library?node-id=411%3A2

**Comment by Moses-Alero** [comment]
Please grant permission to view the design on figma.

**Comment by Oisavictor** [comment]
I have sent you an invite request on figma. Kindly accept to be able to view the design. Thanks

**Comment by Moses-Alero** [comment]
Got it, thanks!

**Comment by Oisavictor** [comment]
You are welcome.
As discussed earlier today, Once you are done with the backend push to the repo so that when you call for the meeting we can look at the code together.
Thanks
