### ISSUE TITLE
Score Sheet Computation

### ISSUE THREAD

**Issue by Oisavictor** [Oisavictor/CGPA-Web-Calculator#3]
# Development of score sheet computation using required data as shown below:
         Courses: Schema --> (Course ID, Course Title, Semester, Session)
         Students: Schema --> (ID, Level, Name, Department, Faculty, Continuous Assessment, Exam Score)
         Staff ID.

## Requirements: 
           The system should calculate the total score of a student for a specified Course using the given data(CA & Exam Score)
           The system should automatically generate and store scoresheet data in the Database

**Comment by Moses-Alero** [comment]
@Oisavictor I think there should be a change to the student and course schema. Such that it looks more like this:

Courses: {
      courseID: string,
      courseTitle: String,
      Semester: String,
      Session: String
      ContinousAssesment: Number,
      Exam Score: Number
}

StudentShema {
      studentID: String,
      Level: String,
      Name: String,
      Department: String,
      Faculty: String,
      Courses: Array (of Courses)     
}


I believe this format will make it easier to create a link between the students and courses. what do you think?
I started writing the API using graphQL about to start creating the database models.

**Comment by Oisavictor** [comment]
Nice suggestion. Please go ahead
